kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
alertmanager:
  persistentVolume:
    enabled: true
server:
  remoteWrite:
    - url: "http://localhost:9201/write"
  remoteRead:
    - url: "http://localhost:9201/read"
  persistentVolume:
    enabled: true
    # storageClass: "sc-efs-csi"
    # existingClaim: "pvc-prometheus"
  extraVolumes:
    - name: "shared-volume"
      emptyDir: {}
  extraVolumeMounts:
    - name: "shared-volume"
      mountPath: "/prometheus"
  sidecarContainers:
    ecs-discovery:
      # image: "gjorgjit/prometheus-ecs-discovery:latest"
      # image: "866021465103.dkr.ecr.eu-central-1.amazonaws.com/prometheus-ecs-discovery:latest"
      args: ["-config.write-to=/mnt/ecs_file_sd.yml"]
      volumeMounts:
        - name: "shared-volume"
          mountPath: "/mnt"
      # env:
      #   - name: "AWS_REGION"
      #     value: "eu-central-1"
    timestream-adapter:
      image: "gjorgjit/prometheus-timestream-adapter:latest"
      ports:
        - name: http
          containerPort: 9201
          protocol: TCP
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "ecs-metrics"
        file_sd_configs:
          - files:
            - "/prometheus/ecs_file_sd.yml"
            refresh_interval: 1m
        metric_relabel_configs:
          - regex: task_arn
            action: labeldrop
# extraScrapeConfigs: |
#   - job_name: "ecs-metrics"
#     file_sd_configs:
#       - files:
#         - "/prometheus/ecs_file_sd.yml"
#         refresh_interval: 1m
#     metric_relabel_configs:
#       - regex: task_arn
#         action: labeldrop
