apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-efs-csi-2
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-010bff1476ba4f7ac
